### ISSUE TITLE
[TypedMongo] Allowing the discriminator field at any position

### ISSUE THREAD

**Issue by pulewicz** [AVSystem/scala-commons#411]
What is the easiest way of reading class hierarchies with discriminator fields at the end of the object? Unfortunately, we need to adapt to an existing schema.

As explained in https://github.com/AVSystem/scala-commons/blob/master/docs/GenCodec.md#flat-sealed-hierarchy-format:

> It may also be sensitive to object field order because the discriminator field must be read before any other fields (this is only a problem with Input implementations that do not support random field access by name - JsonStringInput does not have this problem).

I did some checks, and it seems like `BsonReaderInput` has this problem, but `BsonValueInput` hasn't:  https://github.com/pulewicz/mongo-commons-playground/blob/master/src/main/scala/PlaygroundApp.scala#L47

Questions:

1. Is there any easy way to use `TypedMongoCollection` with value input and output? From what I see currently it's hardcoded and it will need creating your own versions of the following classes, is it correct? 
    
    - https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/GenCodecBasedBsonCodec.scala#L14
    - https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/core/GenCodecProvider.scala#L10
    - https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/core/GenCodecRegistry.scala#L14
    - https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/typed/TypedMongoCollection.scala#L35

3. Is using the value input and output a good solution, or are there any disadvantages?

Regards,
Paweł Ulewicz.

**Comment by ghik** [comment]
Hi,

Thanks for the report. I'll see if I can make `BsonReaderInput` independent of field order similarly to how it's done in `JsonStringInput`. Otherwise I will look for ways make it possible to use `BsonValueInput` in `TypedMongoCollection`. The primary advantage of `BsonReaderInput` over `BsonValueInput` is performance - it avoids the intermediate `BsonValue` representation.

**Comment by pulewicz** [comment]
Hi,

Great to hear that and thanks for help. Please contact me if you need more information.

Regards,
Paweł Ulewicz.

**Comment by ghik** [comment]
Fixed in 2.6.0

**Comment by pulewicz** [comment]
Hi,

Thanks for the info, but how to use the fix? I updated the version to 2.6.0 in my playground app and the `BsonReaderInput` example still doesn't work: https://github.com/pulewicz/mongo-commons-playground/blob/master/src/main/scala/PlaygroundApp.scala#L62

```
com.avsystem.commons.serialization.GenCodec$MissingCase: Cannot read field x of HierarchyTypes.TestType before type field is read
```

Should the reader input work now or should I use the value reader instead? I checked the code in the PR, but there doesn't seem to be anything related to the issue.

Regards,
Paweł Ulewicz.

**Comment by ghik** [comment]
An `ObjectInput` implementation is made immune to field order changes by implementing `peekField`. You can see that done [here](https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonReaderInput.scala#L108). Unfortunately, it doesn't work for `BsonDocumentReader` because of an upstream bug (which I did not manage to properly minimize and report yet).

I assumed that this shouldn't be a problem for users of `TypedMongoCollection` because it uses `BsonBinaryReader` internally (via `GenCodecRegistry`). Do you actually need to use `BsonDocumentReader` besides this test?

**Comment by pulewicz** [comment]
Hi,

I used the `BsonDocumentReader` just for this example for simplicity. I'll try the real code then. Thanks for the info.

Regards,
Paweł Ulewicz.

**Comment by pulewicz** [comment]
It works, thanks!

Regards,
Paweł Ulewicz.
